In [1]:
import numpy as np
a = np.random.randn(5)

In [2]:
print(a)

[ 1.21737233 -0.88092041  0.5289331  -0.22942591  0.6373841 ]


In [3]:
print(a.shape)

(5,)


In [17]:
assert(a.shape == (1,5))
#should give error.. But is not giving it when compared with (1,5)

AssertionError: 

this is rank 1 matrix. It is not row or column vector. It does not say 5,1 or 1,5.. bul leaves second dimension empty

In [4]:
print(a.T)

[ 1.21737233 -0.88092041  0.5289331  -0.22942591  0.6373841 ]


it is same. It is recommended not to use such data structures. So instead generate vector as following.

In [12]:
a = np.random.randn(5,1)
print(a)
print(a.shape)

[[0.11012722]
 [0.40815209]
 [0.4067764 ]
 [0.80756736]
 [0.34972166]]
(5, 1)


In [13]:
assert(a.shape == (5,1))

In [6]:
print(a.T)

[[-0.14067476  0.87229794  0.15054356 -0.42611888  1.64488483]]


In [8]:
print(a * a.T)

[[ 0.01978939 -0.12271031 -0.02117768  0.05994417 -0.23139378]
 [-0.12271031  0.76090369  0.13131883 -0.37170262  1.43482964]
 [-0.02117768  0.13131883  0.02266336 -0.06414945  0.24762681]
 [ 0.05994417 -0.37170262 -0.06414945  0.1815773  -0.70091648]
 [-0.23139378  1.43482964  0.24762681 -0.70091648  2.7056461 ]]


In [9]:
print(np.dot(a, a.T))

[[ 0.01978939 -0.12271031 -0.02117768  0.05994417 -0.23139378]
 [-0.12271031  0.76090369  0.13131883 -0.37170262  1.43482964]
 [-0.02117768  0.13131883  0.02266336 -0.06414945  0.24762681]
 [ 0.05994417 -0.37170262 -0.06414945  0.1815773  -0.70091648]
 [-0.23139378  1.43482964  0.24762681 -0.70091648  2.7056461 ]]


both are same. But likely np.dot would bring more efficiency to the work here.

In [19]:
a = np.random.randn(2, 3)


b = np.random.randn(2, 1)


In [20]:
a+b

array([[ 1.76878134e-01, -1.18253374e-03,  8.44958033e-01],
       [ 1.91874559e+00,  1.89362823e+00,  6.52406942e-01]])

In [21]:
a=np.random.randn(4,3) 
b=np.random.randn(3,2)
a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [22]:
a=np.random.randn(12288,150)
b=np.random.randn(150,45)
c=np.dot(a,b) 

In [23]:
c.shape

(12288, 45)

In [50]:
a = np.arange(12)
a = a.reshape(3,4)
print(a.shape)
print(a)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
b = np.random.randn(4,1)
print(b, b.shape)

[[ 2.3348991 ]
 [-0.64944834]
 [ 1.99087819]
 [-0.93851101]] (4, 1)


In [52]:
a + b.T

array([[ 2.3348991 ,  0.35055166,  3.99087819,  2.06148899],
       [ 6.3348991 ,  4.35055166,  7.99087819,  6.06148899],
       [10.3348991 ,  8.35055166, 11.99087819, 10.06148899]])

In [57]:
a = np.arange(9)
a = a.reshape(3,3)
b = np.arange(3)
b = b.reshape(3,1)
print(a)
print(b)
c = a*b

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]]


In [58]:
print(c)

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]]
